apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-operator
  namespace: {{ .Release.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-operator
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-operator
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}

      containers:
      - name: manager
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
        - /manager
        env:
        - name: IMAGEPULLSECRETS
          value: {{ .Values.imagePullSecrets.name }}
        - name: IMAGE
          valueFrom: 
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: IMAGE
        - name: TAG
          valueFrom: 
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: TAG
        - name: BROKERS
          valueFrom: 
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: BROKERS
        - name: TOPIC
          valueFrom: 
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: TOPIC
        - name: APP_LABEL
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: APP_LABEL
        - name: TOPOLOGY_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: TOPOLOGY_KEY
        - name: CPU_REQUEST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: CPU_REQUEST
        - name: CPU_LIMIT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: CPU_LIMIT
        - name: MEMORY_REQUEST
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: MEMORY_REQUEST
        - name: MEMORY_LIMIT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-config
              key: MEMORY_LIMIT
              
        
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}

      serviceAccountName: {{ .Values.serviceAccount.name }}
