apiVersion: grm.csye7125.local/v1alpha1
kind: GithubRelease
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.GR.name }}
    app.kubernetes.io/managed-by: Helm
  name: {{ .Values.GR.name }}
spec:
  url: {{ .Values.GR.url }}
