kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: {{ .Release.namespace }}
  name: limit-operator-access
spec:
  podSelector: {}
  egress:
  - to:
    - ipBlock: 
        cidr: 0.0.0.0/0
  - to:
    - namespaceSelector: {}
  - to:
    - namespaceSelector:
        matchLabels:
          name: cve-consumer
    ports: []
    
  policyTypes:
    - Egress
