apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Release.Namespace }}
type: {{ .Values.imagePullSecrets.type }}
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerConfig}}
